import 'package:firebase_core/firebase_core.dart';

/// Replace the placeholder values below with the actual Firebase configuration
/// generated by the FlutterFire CLI for each supported platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyBlz9GjYQJ1wwRgg2GvV3eNwqnW6yQjhDM',
      appId: '1:3665717388:android:3fd749d4546151c67bb3a9',
      messagingSenderId: '3665717388',
      projectId: 'alroy-fca95',
      storageBucket: 'alroy-fca95.firebasestorage.app',
    );
  }
}
